### ISSUE TITLE
Модуль не меняет статус заказа после "оплаты"

### ISSUE THREAD

**Issue by afwollis** [begateway/opencart-1.5-payment-module#1]
EDITED_2.

Не заходит в блок
if ($this->is_authorized() && $order_info) { ... }
потому что вот этот метод
```
  protected function is_authorized() {
    $username=$this->config->get('begateway_companyid');
    $password=$this->config->get('begateway_encryptionkey');
    if (isset($_SERVER['PHP_AUTH_USER']) && isset($_SERVER['PHP_AUTH_PW'])) {
      return $_SERVER['PHP_AUTH_USER'] == $username &&
             $_SERVER['PHP_AUTH_PW'] == $password;
    }

    return false;
  }
```
постоянно возвращает false.

**Comment by avsh** [comment]
Добавьте в .htaccess 

RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteRule .* - [E=REDIRECT_HTTP_AUTHORIZATION:%{HTTP:Authorization}]
